comment:
  image:
    repository: raian13/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: raian13/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: raian13/ui
    tag: latest
    service:
      externalPort: 9292
