apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name:  {{ template "zipkin.fullname" . }}
  labels: 
    app: reddit
    component: zipkin
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: zipkin
      release: {{ .Release.Name }}      
  template:
    metadata:
      name: zipkin-pod
      labels:
        app: reddit
        component: zipkin
        release: {{ .Release.Name }}        
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: zipkin
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: zipkin
          protocol: TCP          
          