---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "zipkin.fullname" . }}
  labels:
    app: reddit
    component: zipkin
    release: {{ .Release.Name }}   
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: zipkin
    release: {{ .Release.Name }}   
    