version: '3.3'
services:

  prometheus:
    image: ${USER_NAME}/prometheus
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    ports:
      - '9090:9090'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter
    user: root
    deploy:
      mode: global
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  grafana:
    image: grafana/grafana
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back_net

volumes:
  grafana_data:

networks:
  back_net:
  front_net:
